version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 50
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
          - "@smithy/*"
