name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Check License Pollution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: true
      - run: pnpm jsgl --local ./packages/vitest-dynamodb-lite/
