name: release

on:
  workflow_dispatch:
    inputs:
      bumpType:
        description: Bump Type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 10
          run_install: true
      - run: pnpm test
      - name: Configure git user
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - name: Bump package.json version
        id: bump
        run: |
          cd packages/vitest-dynamodb-lite
          pnpm version ${{ github.event.inputs.bumpType }}
          echo "VERSION=v$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
      - name: Commit and Push
        run: |
          git commit -am "Bump version up to ${{ steps.bump.outputs.VERSION }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag and Push
        run: |
          git tag ${{ steps.bump.outputs.VERSION }}
          git push --tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # We need to update npm for trusted publishing because pnpm publish uses npm under the hood.
      # see https://docs.npmjs.com/trusted-publishers
      - name: Update npm
        run: npm install -g npm@latest

      - name: Release
        run: |
          cd packages/vitest-dynamodb-lite
          pnpm publish

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Get commit summary
        id: get_commit_summary
        run: |
          PREVIOUS_TAG=$(git tag --sort=-creatordate | sed -n 2p)
          echo "PREVIOUS_TAG: $PREVIOUS_TAG"
          COMMIT_SUMMARY="$(git log --oneline --pretty=tformat:"%h %s" $PREVIOUS_TAG..${{ github.ref }})"
          COMMIT_SUMMARY="${COMMIT_SUMMARY//$'\n'/'%0A'}"
          echo ::set-output name=COMMIT_SUMMARY::$COMMIT_SUMMARY
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ${{ steps.get_commit_summary.outputs.COMMIT_SUMMARY }}
          draft: true
          prerelease: true
